name: nix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build hybrid-node
        run: nix build .#hybrid-node --print-build-logs
      - name: flake check
        run: nix flake check --print-build-logs
